import type { Metadata } from 'next';
import { Josefin_Sans } from 'next/font/google';
import './globals.css';
import Image from 'next/image';
import bgDesktopDark from "@/public/images/bg-desktop-dark.jpg";
import TasksContextProvider from '@/context/tasks-context';

const josefin_sans = Josefin_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${josefin_sans.className} relative bg-veryDarkBlue`}>
      <Image className="absolute left-0 top-0 -z-10" src={bgDesktopDark} alt="bg image"/>

      <TasksContextProvider>
        {children}
      </TasksContextProvider>
      
      </body>
    </html>
  )
}
